#!/usr/bin/env bash
# Create a new certificate authority root.
# We use 4096-bit RSA because MacOS does not yet support EC keys!
VAPR_DATA_DIR_build=`pwd`/build ./dockertools/bin/run caroot.docker caroot bash -c "
echo \"[ alt_name ]\" >> /etc/ssl/openssl.cnf
echo \"IP.1 = 255.255.255.255\" >> /etc/ssl/openssl.cnf

cd build
mkdir -p private newcerts crl
chmod go-rx private
touch index.txt
echo 01 >> serial
openssl genrsa -des -out private/ca.key 4096 &&
openssl req -new -x509 -days 3300 -key private/ca.key -out ca.crt
chmod go-rx private/*
cp ca.crt /vapr/certstore
"
