#!/usr/bin/env bash
# Sign a file.
SCRIPT_DIR=$(cd $(dirname $0); pwd)
VAPR_DATA_DIR_build=${SCRIPT_DIR}/build VAPR_DATA_DIR_disk=/ ./dockertools/bin/run caroot.docker caroot bash -c "
FILENAME=\"$1\"
RELDIR=`pwd`
if [[ -z \"\${FILENAME}\" ]]; then
    echo Usage:
    echo $0 file_to_sign
    exit 1
fi

mkdir -p build/signed

cd disk\${RELDIR}
if [ \${FILENAME:0:1} == "/" ]; then
    FILENAME=\"\${FILENAME#/}\"
    cd /vapr/disk
fi
openssl cms -inkey /vapr/build/private/codesign.key -sign -binary -noattr -signer /vapr/build/newcerts/codesign.crt -certfile /vapr/build/ca.crt -outform DER -in \${FILENAME} -out \${FILENAME}.sig
"